theme: osuny-hugo-theme-aaa
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  search:
    active: false  
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logofooter.svg"