theme: osuny
_merge: deep
params:
  summary:
    position: hero
  breadcrumb:
    position: after-hero
  search:
    active: false
  logo:
    header: "/assets/images/logo.svg"
    footer: "/assets/images/logofooter.svg"